---
title: "13.Data Challenge 2: Natural Earth"
author: "Sung Inkyung"
date: '2021 11 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rnaturalearth)
library(sf)
library(MetBrewer)
library(janitor)
library(showtext)

font_add_google("Caveat Brush")
font_add_google("Caveat")
font_add_google("Sarabun")
```


```{r}
happiness <- read.csv("data/WHR20_DataForTable2.1.csv") %>% 
  clean_names() %>% 
  select(year, country_name, life_ladder, 
         sd_mean = standard_deviation_of_ladder_by_country_year)

world <- map_data("world")
korea_map <- ne_countries(scale = "medium",
                          returnclass = "sf") %>% 
  filter(sovereignt == "South Korea")
  

plot_df <- left_join(korea_map, happiness, 
                        by = c("sovereignt" = "country_name")) %>% 
  group_by(year) %>% 
  mutate(life = mean(life_ladder))
```


```{r}
p <-plot_df %>% 
  ggplot() +
  geom_sf(aes(fill = life), 
          alpha = 0.6) +
  scale_fill_gradientn(colors = met.brewer("Gauguin")) +
  facet_wrap(~ year,
             nrow = 1) +
  coord_sf() +
  labs(title = "Happiness in South Korea",
       subtitle = "Yearly average of life ladder score from 10(best) to 0(worst)",
       caption = "Source: World Happiness Report | Graphic: Sung Inkyung") +
  guides(fill = guide_colorbar(
    title = "Life ladder",
    title.position = "top",
    barwidth = 9,
    barheight = .5
  )) +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.background = element_rect(fill = "#FFF8E7",
                                     color = NA),
    legend.direction = "horizontal",
    legend.title.align = 0.5,
    strip.text = element_text(size = 15, 
                              family = "Caveat Brush"),
    plot.background = element_rect(fill = "#FFF8E7", color = NA),
    plot.title = element_text(size = 30,
                              family = "Caveat Brush",
                              hjust = 0.5, 
                              color = "#00ab4c",
                              face = "bold"),
    plot.subtitle = element_text(size = 16, 
                                 family = "Caveat",
                                 hjust = 0.5,
                                 margin = margin(b = 15)),
    plot.caption = element_text(size = 8, 
                                family = "Sarabun",
                                hjust = 1.17,
                                 margin = margin(t = 20)),
    plot.margin = margin(10, 10, 10, 10))

ggsave("KoreaHappiness.png", width = 30, height = 8, units = "cm")
```
