---
title: "28.The Earth is not flat"
author: "Sung Inkyung"
date: '2022 1 14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[30DayMapChallenge by @gkaramanis](https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/28-not-flat/28-not-flat-circle.R)
```{r}
library(tidyverse)
library(lubridate)
library(showtext)

font_add_google("Orbitron")
font_add_google("Montserrat Alternates")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r replicate plot by @gkaramanis}
centroids <- read_csv("data/country_centroids.csv") %>%
  mutate(
    a = longitude * pi/180,
    d = ifelse(country == "ID", 2, 1.3),
    h = ifelse(abs(a) < pi/2, 0, 1))
    # name = str_wrap(name, 30)


longs <- data.frame(
  l = seq(-180, 180, 90)
) %>% 
  mutate(la = 1 * pi/180)
```


```{r replicate plot by @gkaramanis}
ggplot(centroids) +
  geom_segment(aes(x = cos(a), xend = 0.999 * d * cos(a),
                   y = sin(a), yend = 0.999 * d * sin(a)),
               size = 0.05) +
  geom_point(aes(x = cos(a), y = sin(a)), size = 0.2) +
  geom_text(aes(x = d * cos(a), y = d * sin(a),
                label = ifelse(h == 0, paste("·", name), paste(name, "·")),
                hjust = h,
                angle = ifelse(h == 0, longitude, longitude - 180),
                color = ifelse(name == "Indonesia", "#07711e", "grey10")),
            check_overlap = TRUE, size = 3,
            family = "Orbitron", lineheight = 0.9) +
  geom_text(data = longs,
            aes(x = 0.85 * cos(la), y = 0.85 * sin(la),
                label = ifelse(l == -180,  "±180", l)),
            check_overlap = TRUE, 
            family = "Montserrat Alternates",
            size = 3.5) +
  annotate("text",
           0, 0,
           label = "The\nEarth\nis not\nflat",
           family = "Orbitron",
           size = 15, fontface = "bold",
           lineheight = 0.9) +
  scale_color_identity() +
  coord_fixed(xlim = c(-2, 2), ylim = c(-2, 2),
              clip = "off") +
  labs(caption = "Source: Longitude of country centroids | Credit: @gkaramanis") +
  theme_void() +
  theme(plot.background = element_rect(fill = "gray97",
                                       color = NA),
        plot.caption = element_text(family = "Orbitron",
                                    hjust = 0.5),
        plot.margin = margin(20, 20, 20, 20))

ggsave("Indonesia.png", width = 26, height = 27, units = "cm")

### This plot is my favorite one among all the contributions to #30DayMapChallenge. The changes I made is typeface and cleaning up data.
```

