---
title: "Du Bois Challenge"
author: "Sung Inkyung"
date: '2021 2 28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by rjstevick] (https://github.com/rjstevick/TidyTuesday/blob/master/2021/20210216_DuBoisChallenge/tidytuesday_20210216.R#L27)
### Source[Data Visualization by Kieran Healy] (https://socviz.co/maps.html#maps)
### https://medium.com/nightingale/discovering-a-new-chart-from-w-e-b-du-boiss-the-exhibition-of-american-negros-part-6-66e7b340b90c
```{r}
library(tidyverse)
```


```{r}
tuesdata <- read_csv('https://raw.githubusercontent.com/ajstarks/dubois-data-portraits/master/plate02/data.csv')

```


```{r}
tuesdata %>% 
  count(Population, sort = T) %>% 
  arrange(Population)

# function to increase vertical spacing between legend keys by @clauswilke.
# https://stackoverflow.com/questions/11366964/is-there-a-way-to-change-the-spacing-between-legend-items-in-ggplot2

draw_key_polygon3 <- function(data, params, size) {
  lwd <- min(data$size, min(size) / 4)
  grid::rectGrob(width = grid::unit(0.6, "npc"), 
                 height = grid::unit(0.6, "npc"),
                 gp = grid::gpar(col = data$colour, 
                                 fill = alpha(data$fill, data$alpha), 
                                 lty = data$linetype, 
                                 lwd = lwd * .pt, 
                                 linejoin = "mitre"))}

plot <- tuesdata %>% 
  left_join(data.frame(state.abb, state.name), 
            by = c("State" = "state.abb")) %>% 
  mutate(region = tolower(state.name),
         Population = factor(Population,
                             levels = c("750,000 AND OVER",
                                        "600,000 - 750,000",
                                        "500,000 - 600,000",
                                        "300,000 - 500,000",
                                        "200,000 - 300,000",
                                        "50,000 - 100,000",
                                        "25,000 - 50,000",
                                        "10,000 - 25,000",
                                        "UNDER - 10,000"))) %>% 
  left_join(map_data("state")) %>% 
  ggplot(aes(long, lat, group = group, 
             fill = Population)) +
  geom_polygon(color = "gray25",
               size = .1,
               key_glyph = "polygon3") +
  theme_void() +
  coord_map(projection = "albers",
            lat0 = 39, lat1 = 45) +
   scale_fill_manual(values = c("#000000", "#bebdb8", "#f2f2f2", "#63400f", "#252854", "#b21e4b", "#f5cfc6", "#fcd30d", "#c4b59f")) +
  guides(fill = guide_legend(ncol = 2)) +
  labs(title = "RELATIVE NEGRO POPULATION OF\nTHE STATES OF THE UNITED STATES.", 
       fill = " ",
       caption = "Source: Du Bois Challenge | Graphic: Sung Inkyung") +
  theme(legend.position = "bottom", 
        legend.text = element_text(color = "grey20"),
        legend.key.size = unit(1, "cm"),
        legend.spacing.y = unit(.5, "cm"),
        plot.title = element_text(size = 18,
                                  hjust = 0.5, 
                                  face = "bold",
                                  margin = margin(t = 10, 
                                                  b = 20)),
        plot.caption = element_text(size = 8, 
                                    hjust = 0.5, 
                                    margin = margin(t = 20)))

ggsave(filename = "relativepopulationofblacks.png", width = 21, height = 13, units = "cm")

  
  
```
