---
title: "Giant Pumpkins"
author: "Sung Inkyung"
date: '2022 1 3'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[Cartograms in ggplot2 by R CHARTS] (https://r-charts.com/spatial/cartogram-ggplot2/)
```{r}
library(tidyverse)
library(cartogram)
library(sf)
library(albersusa)
library(ragg)
library(showtext)
theme_set(theme_minimal())

#add fonts
font_add_google(name = "Quicksand", family = "quicksand")

showtext_auto()
```

```{r}
pumpkins <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-10-19/pumpkins.csv')

df <- pumpkins %>% 
  separate(id, c("year", "type"), sep = "-") %>% 
  mutate(weight_lbs = parse_number(weight_lbs)) %>% 
  filter(!is.na(weight_lbs))


df_pumpkins <- df %>% 
  filter(type == "P",
         country == "United States",
         year == 2021) %>% 
  group_by(state_prov) %>% 
  summarise(weight = max(weight_lbs),
            log_weight = log10(weight),
            log_weight = round(log_weight, 2)) %>% 
  rename(state = state_prov)


usa <- usa_sf() %>% 
  st_transform(3857) %>%
  left_join(df_pumpkins, by = c("name" = "state")) %>% 
  filter(!is.na(log_weight)) %>% 
  filter(name != "District of Columbia") %>% 
  filter(name != "Alaska") %>% 
  filter(name != "Hawaii")

us_cartogram <- cartogram_cont(usa, "log_weight")
  

labels <- us_cartogram %>% 
  filter(log_weight > 3.33) %>% 
  mutate(name = str_to_upper(name))

plot <- ggplot(us_cartogram) +
  geom_sf(aes(fill = log_weight), color = "#eeeed1", size = 0.1) +
  geom_sf_text(data = labels,
               aes(label = name),
               family = "quicksand", ,
               size = 5,
               color = "#2d3047") +
  scale_fill_gradient(
    high = "#ff7518", low = "#e0b094",
    guide = guide_colorsteps(
      barwidth = 5.5,
      barheight = 0.3,
      title = "Log10 Weight(lb)",
      title.position = "top",
      title.hjust = 0.5)) +
  labs(x = "",
       y = "",
       title = "Giant Pumpkins in 2021",
       caption = "Source: BigPumpkins.com | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "bottom",
        legend.background = element_rect(fill = "#eee8cd", 
                                         color = NA),
        plot.background = element_rect(fill = "#eee8cd", 
                                       color = NA), 
        panel.background = element_rect(fill = "#eee8cd", 
                                        color = NA),
        plot.title = element_text(size = 35, 
                                  family = "quicksand",
                                  face = "bold",
                                  color = "#2d3047",
                                  margin = margin(b = 10)),
        plot.caption = element_text(size = 12,
                                    family = "quicksand",
                                    color = "#81706b",
                                    margin = margin(t = 15)),
        plot.margin = margin(10, 10, 10, 10))

ggsave("GiantPumpkins.png", width = 9, height = 7, units = "cm", dpi = 300)
```

