---
title: "Transit Cost Project"
author: "Sung Inkyung"
date: '2021 2 6'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by Jack Davision] (https://jack-davison.github.io/posts/2021-01-05-tidytuesday-2021-week-2-global-transit-costs/)
```{r}
library(tidyverse)
library(tidytuesdayR)
library(countrycode)
library(rnaturalearth)
library(maps)
library(leaflet)
library(htmltools)

```


```{r}
world <- ne_countries(scale = "medium",
                      returnclass = "sf") %>% 
  filter(!continent %in% c("Antarctica", "Seven seas (open ocean"))

continents <- countrycode::codelist %>% 
  select(ecb, country.name.en, continent) %>% 
  rename(country = country.name.en) 


cities <- maps::world.cities %>% 
  select(city = name, 
         country = country.etc,
         lat, 
         lng = long)

df <- tt_load("2021-01-05")$transit_cost %>% 
  rename(ecb = country) %>% 
  mutate(ecb = if_else(ecb == "UK", "GB", ecb)) %>% 
  left_join(continents, by = "ecb") %>% 
  left_join(cities, by = c("city", "country")) %>% 
  filter(lat != "na") %>% 
  mutate(start_year = as.numeric(start_year)) %>% 
  filter(start_year > 2000) %>% 
  select(city, country, continent, lat, lng, cost_km_millions) %>%
  group_by(city, country, continent, lat, lng) %>%
  summarise(avg = median(cost_km_millions)) %>%
  ungroup() %>%
  as.data.frame()



leaflet(df) %>%
  addTiles() %>%
  addCircles(data = df, lng = ~lng, lat = ~lat,
             radius = ~round(avg,0) * 200) %>%
  addMarkers(lng = ~lng, lat = ~lat, 
             clusterOptions = markerClusterOptions(),
             popup = ~paste0("<b>", city, "</b>, ",country,"<br>",
                             "$",round(avg,0)," million / km"))
  
```



```{r}
Plot_world <-  df %>% 
  ggplot() +
  geom_sf(data = world, color = "white", fill = "#bdaf90") +
  geom_point(aes(lng, lat, 
                 group = city,
                 size = avg,
                 color = continent),
             alpha = .6) +
  scale_color_manual(values = c("Africa" = "#daa520", 
                                "Asia" = "#ff7373", 
                                "Europe" = "#008080",
                                "Oceania" = "#c3beff", 
                                "Americas" = "#064a89")) +
  scale_size(range = c(1,10), 
             limits = c(60,1650)) +
  guides(color = guide_none()) +
  labs(title = "Rail Transit Cost in World Cities",
       subtitle = "Median Cost by millions of USD per kilometer.",
       size = " ",
       caption = "Source:TransitCosts.com | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "top", 
        legend.text = element_text(hjust = 0),
        legend.spacing.x = unit(0.5, 'cm'),
        plot.title = element_text(size = 20,
                                  hjust = .5),
        plot.subtitle = element_text(size = 16,
                                     hjust = .5),
        plot.caption = element_text(size = 9,
                                    margin = margin(t = 15, 
                                                    b = 20)))
```


```{r}
library(ggpubr)

plot_conts <-  function(world_cont, data_cont){
  
  df_conts <- df %>%
    filter(!is.na(continent)) %>%
    filter(continent == data_cont)
  
  df_max = filter(df_conts, avg == max(avg))
  
  df_min = filter(df_conts, avg == min(avg))
  
  ggplot(df_conts) +
    geom_sf(data = world %>% 
              filter(continent %in% world_cont), 
            color = "white", 
            fill = "#bdaf90") +
    geom_point(aes(lng, lat, 
                   group = city,
                   size = avg,
      color = if_else(city %in% c(df_max$city, df_min$city), 
                      continent, "white")),
      alpha = .75) +
    scale_color_manual(values = c("Africa" = "#daa520", 
                                "Asia" = "#ff7373", 
                                "Europe" = "#008080",
                                "Oceania" = "#c3beff", 
                                "Americas" = "#064a89",
                                "white" = "gray55")) +
    scale_size(range = c(1,10), 
               limits = c(60,1650)) +
    guides(color = guide_none()) +
    labs(size = "Million $ / km",
         title = paste0("Max: ", df_max$city, " ($", round(df_max$avg), "/km)\n",
                        "Min: ", df_min$city, " ($", round(df_min$avg), "/km)")) +
    theme(legend.position = "none",
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text = element_blank())
  
}


americas <-  plot_conts(world_cont = c("North America"), 
                         data_cont = "Americas") +
  coord_sf(xlim = c(-140, -50), ylim = c(-40, 60))

europe<-  plot_conts(world_cont = c("Europe"), data_cont = "Europe") +
  coord_sf(xlim = c(-10, 45), ylim = c(38, 60))

asia <-  plot_conts(world_cont = c("Asia"), data_cont = "Asia") +
  coord_sf(xlim = c(30, 140), ylim = c(-10,50))

p <-  ggarrange(americas, europe, asia, nrow = 1)

ggarrange(Plot_world, p, 
          ncol = 1, 
          heights = c(2,1), 
          align = "hv")

ggsave(filename = "Transitcost.png", width = 20, height = 17, units = "cm")
```

```{r}
df %>% 
  filter(continent == "Americas") %>% 
  count(lat, sort = T)

```
